"""The public site, built from the repository's own documents.

Generated rather than hand-written, for the same reason `docs/reference/` is: a page
describing a renamed command reads perfectly and sends every reader to something that does
not exist.

The tests are about the renderer's failures, because a documentation build fails silently
by definition — it produces a page, the page loads, and the only person who notices the
paragraph structure is wrong is a reader who has already decided the project is careless.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

from build_site import PAGES, inline, markdown


def test_a_wrapped_paragraph_is_one_paragraph() -> None:
    """These documents wrap at ninety columns.

    Treating each line as its own paragraph put a gap between every wrapped line and made
    the whole site read as a list of sentences — which is what the first build did.
    """
    rendered = markdown("A sentence that continues\non the following line.")

    assert rendered.count("<p>") == 1
    assert "continues on the following" in rendered


def test_a_blank_line_starts_a_new_paragraph() -> None:
    """The other half: joining everything would run the whole document together."""
    assert markdown("First.\n\nSecond.").count("<p>") == 2


def test_a_multi_line_quotation_is_one_quotation() -> None:
    """Rendering each line as its own blockquote put a rule between every wrapped line of
    the README's opening, which read as three quotations from three different places."""
    rendered = markdown("> One line\n> and its continuation.")

    assert rendered.count("<blockquote>") == 1


def test_html_comments_do_not_reach_the_page() -> None:
    """`docs/reference/` opens with a "generated, do not edit by hand" comment aimed at
    somebody reading the file. It rendered as the first paragraph of the published page —
    an instruction to the wrong audience, at the top of what they came to read."""
    rendered = markdown("<!-- do not edit by hand -->\n\n# Title\n")

    assert "do not edit" not in rendered
    assert "<h1>Title</h1>" in rendered


def test_a_table_renders_as_a_table() -> None:
    rendered = markdown("| a | b |\n| --- | --- |\n| 1 | 2 |\n")

    assert "<table>" in rendered and "<th>a</th>" in rendered and "<td>1</td>" in rendered


def test_a_code_fence_is_escaped_not_interpreted() -> None:
    """A page that renders `<script>` from a code block is a page that executes whatever a
    document happens to contain."""
    rendered = markdown("```\n<script>alert(1)</script>\n```")

    assert "&lt;script&gt;" in rendered
    assert "<script>" not in rendered


def test_emphasis_inside_code_is_left_alone() -> None:
    """`**kwargs` is an argument, not bold text — and Python documents are full of it."""
    assert "<strong>" not in inline("`**kwargs`")


def test_a_repository_link_lands_on_a_page() -> None:
    assert 'href="prd.html"' in inline("[the PRD](docs/PRD.md)")


def test_an_external_link_is_left_alone() -> None:
    assert 'href="https://example.test/x"' in inline("[x](https://example.test/x)")


def test_an_unknown_repository_link_is_not_rewritten() -> None:
    """A dead link a reader can see beats a silent rewrite to a page that does not exist."""
    assert 'href="docs/nothing.md"' in inline("[x](docs/nothing.md)")


def test_an_image_path_points_at_the_copied_directory() -> None:
    assert 'src="images/a.png"' in inline("![a](docs/images/a.png)")


def test_every_page_has_a_source_or_is_a_generated_report(tmp_path: Path) -> None:
    """A page whose source moved 404s for every reader while the build reports success.

    Reports written by a trial run are allowed to be absent — they are generated by a
    command that needs a live model — but everything else must exist in the repository.
    """
    generated = {"trials", "product-trial", "stress"}
    missing = [p.slug for p in PAGES if not p.source.is_file() and p.slug not in generated]

    assert missing == [], f"these pages have no source: {missing}"


@pytest.mark.integration
def test_the_site_builds(tmp_path: Path) -> None:
    """End to end, through the same entry point CI uses."""
    out = tmp_path / "_site"
    result = subprocess.run(
        [sys.executable, "scripts/build_site.py", "--out", str(out)],
        cwd=Path(__file__).resolve().parent.parent,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert (out / "index.html").is_file()
    assert (out / ".nojekyll").is_file(), "Jekyll would drop anything under an underscore"
    index = (out / "index.html").read_text(encoding="utf-8")
    assert "<title>Software Factory</title>" in index
    assert 'href="cli.html"' in index
