"""Multi-agent orchestration patterns (PRD FR-30).

A factory that can only run one agent at a time through one linear path can do one thing
well and nothing else. The named patterns -- fan-out/fan-in, a dependency graph, a swarm,
a critic, a supervisor with workers -- are how a fleet is actually put to work, and until
now each would have had to be hand-wired by whoever needed it.

**They are one mechanism, not five.** A plan is a set of steps, the edges between them, and
a rule for reading the results. Every named pattern is a shape of that:

  fan-out/fan-in   N independent steps, then a join
  dag              arbitrary edges
  swarm            N independent steps with the *same* task, joined by score
  critic           producer -> critic, joined on the critic's verdict
  supervisor       planner -> N workers -> join

Writing them as five engines would mean five places for the same bug. Writing them as five
constructors over one engine means a fix to cycle detection fixes all of them at once, and
the differences between the patterns stay visible as what they are: a shape and a join rule.

Six decisions, each one a failure this module exists to avoid:

**A cycle is refused when the plan is built, not discovered when it deadlocks.** A plan that
hangs gives an operator a stuck fleet and no error; a plan that refuses gives them the two
step names that point at each other.

**The join rule is always declared.** There is no default. A fan-in that quietly accepts the
first success turns a five-way check into a one-way one, and the four steps that disagreed
are paid for and discarded. `ALL`, `ANY`, `QUORUM(n)` and `BEST` are different questions and
nobody can guess which was meant.

**A step that never ran is `SKIPPED`, not `FAILED`.** They mean different things -- "we
tried and it did not work" against "we never found out" -- and a join that counts skips as
failures reports a plan that was tested and rejected when it was actually abandoned.

**A swarm is scored, never raced.** First-past-the-post selects for speed, and the fastest
answer is the one that did the least work. A swarm with no scorer is a swarm that picks
whichever machine was least busy.

**A critic may not be the producer.** The same agent judging its own output is a rubber
stamp with a latency cost, and it is the single easiest way to build a review step that
never rejects anything.

**Every child step carries the plan and the parent.** A fan-out of twenty otherwise appears
in the ledger as twenty unrelated runs, and the cost of the whole operation is unattributable
-- which is precisely the number somebody will ask for after the bill arrives.
"""

from __future__ import annotations

import enum
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from typing import Any

from software_factory.errors import ErrorCode, FactoryError

#: How many steps one plan may hold. A bound rather than a guess: a plan is written by
#: hand or generated by a supervisor, and a supervisor that emits ten thousand steps has
#: misunderstood the task in a way that should stop rather than bill.
MAX_STEPS = 200


class PatternError(FactoryError):
    """A plan this factory will not run."""

    code = ErrorCode.DEFINITION_INVALID


class Join(enum.StrEnum):
    """How a plan reads the results of the steps that fed into it.

    Never defaulted. Each is a different question, and picking one on the caller's behalf
    silently answers a question they did not ask.
    """

    ALL = "all"
    ANY = "any"
    QUORUM = "quorum"
    BEST = "best"


class StepState(enum.StrEnum):
    """What became of one step.

    `SKIPPED` is separate from `FAILED` on purpose. "We tried and it did not work" and "we
    never found out" lead to different next actions, and a join that folds them together
    reports a plan that was tested and rejected when it was abandoned.
    """

    SUCCEEDED = "succeeded"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass(frozen=True, slots=True)
class Step:
    """One unit of work in a plan.

    `needs` names steps rather than indices. An index is stable until somebody reorders the
    list, and a dependency that silently repoints at a different step is a plan that runs
    successfully and does the wrong thing.
    """

    name: str
    request: str
    agent: str = ""
    requires: tuple[str, ...] = ()
    needs: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not self.name.strip():
            raise PatternError(
                "a step needs a name",
                remediation="Names are how dependencies and results are addressed.",
            )
        if not self.request.strip():
            raise PatternError(
                f"step {self.name!r} has no request",
                remediation="Say what the step should do. An empty request is a run that bills.",
            )


@dataclass(frozen=True, slots=True)
class Outcome:
    """What one step produced."""

    step: str
    state: StepState
    detail: str = ""
    score: float | None = None
    payload: Any = None

    @property
    def ok(self) -> bool:
        return self.state is StepState.SUCCEEDED

    def as_dict(self) -> dict[str, Any]:
        return {
            "step": self.step,
            "state": self.state.value,
            "detail": self.detail,
            "score": self.score,
        }


@dataclass(frozen=True, slots=True)
class PlanResult:
    """What a whole plan produced, and whether it counts as satisfied."""

    plan: str
    satisfied: bool
    reason: str
    outcomes: tuple[Outcome, ...] = ()
    chosen: Outcome | None = None

    @property
    def succeeded(self) -> tuple[Outcome, ...]:
        return tuple(o for o in self.outcomes if o.ok)

    @property
    def failed(self) -> tuple[Outcome, ...]:
        return tuple(o for o in self.outcomes if o.state is StepState.FAILED)

    @property
    def skipped(self) -> tuple[Outcome, ...]:
        return tuple(o for o in self.outcomes if o.state is StepState.SKIPPED)

    def as_dict(self) -> dict[str, Any]:
        return {
            "plan": self.plan,
            "satisfied": self.satisfied,
            "reason": self.reason,
            "outcomes": [o.as_dict() for o in self.outcomes],
            "chosen": self.chosen.as_dict() if self.chosen else None,
        }


@dataclass(frozen=True)
class Plan:
    """Steps, the edges between them, and how to read the result.

    Validated at construction. Every check here is one a runtime would otherwise discover
    by hanging, and a fleet that hangs gives an operator no error to act on.
    """

    name: str
    steps: tuple[Step, ...]
    join: Join
    quorum: int = 0
    pattern: str = "dag"

    def __post_init__(self) -> None:
        if not self.steps:
            raise PatternError(
                f"plan {self.name!r} has no steps",
                remediation="A plan with nothing in it succeeds without doing anything.",
            )
        if len(self.steps) > MAX_STEPS:
            raise PatternError(
                f"plan {self.name!r} has {len(self.steps)} steps (limit {MAX_STEPS})",
                remediation=(
                    "Split it, or check whether whatever generated this plan understood "
                    "the task. A plan this size costs more to run than to reconsider."
                ),
            )
        names = [step.name for step in self.steps]
        duplicates = sorted({n for n in names if names.count(n) > 1})
        if duplicates:
            raise PatternError(
                f"two steps are named {', '.join(duplicates)}",
                remediation="Names address dependencies and results; give each step its own.",
            )
        known = set(names)
        for step in self.steps:
            unknown = sorted(set(step.needs) - known)
            if unknown:
                raise PatternError(
                    f"step {step.name!r} needs unknown step(s): {', '.join(unknown)}",
                    remediation=(
                        "A dependency on a step that does not exist would wait forever. "
                        f"Known steps: {', '.join(sorted(known))}."
                    ),
                )
            if step.name in step.needs:
                raise PatternError(
                    f"step {step.name!r} depends on itself",
                    remediation="Remove it from its own `needs`.",
                )
        if self.join is Join.QUORUM:
            if self.quorum < 1:
                raise PatternError(
                    f"plan {self.name!r} joins on a quorum of {self.quorum}",
                    remediation=(
                        "State how many must succeed. A quorum of zero is satisfied by a "
                        "plan where every step failed."
                    ),
                )
            if self.quorum > len(self.steps):
                raise PatternError(
                    f"plan {self.name!r} needs {self.quorum} of {len(self.steps)} steps",
                    remediation=(
                        "A quorum larger than the plan can never be met, so the plan is "
                        "guaranteed to fail after paying for every step."
                    ),
                )
        self.order()  # Raises on a cycle, at construction rather than at a deadlock.

    # ------------------------------------------------------------------ ordering

    def order(self) -> tuple[tuple[Step, ...], ...]:
        """Steps in dependency order, grouped into waves that may run together.

        Waves rather than a flat list, because the parallelism is the point: a fan-out of
        twenty returns one wave of twenty, and a caller that wants them concurrent has the
        grouping without having to recompute it.

        Raises on a cycle, naming the steps involved. Detected here rather than by a runtime
        timeout: a plan that hangs gives an operator a stuck fleet and nothing to read.
        """
        remaining = {step.name: set(step.needs) for step in self.steps}
        by_name = {step.name: step for step in self.steps}
        waves: list[tuple[Step, ...]] = []
        done: set[str] = set()
        while remaining:
            ready = sorted(name for name, needs in remaining.items() if needs <= done)
            if not ready:
                stuck = ", ".join(sorted(remaining))
                raise PatternError(
                    f"plan {self.name!r} has a dependency cycle among: {stuck}",
                    remediation=(
                        "These steps wait on each other, so none can start. Break the "
                        "loop by removing one edge."
                    ),
                )
            waves.append(tuple(by_name[name] for name in ready))
            done |= set(ready)
            for name in ready:
                del remaining[name]
        return tuple(waves)

    @property
    def width(self) -> int:
        """The widest wave: how many steps could run at once."""
        return max(len(wave) for wave in self.order())

    def as_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "pattern": self.pattern,
            "join": self.join.value,
            "quorum": self.quorum or None,
            "width": self.width,
            "steps": [
                {
                    "name": step.name,
                    "agent": step.agent,
                    "needs": list(step.needs),
                    "requires": list(step.requires),
                }
                for step in self.steps
            ],
        }


# ------------------------------------------------------------------------ constructors


def fan_out(
    name: str,
    requests: Sequence[str],
    *,
    join: Join,
    quorum: int = 0,
    agent: str = "",
    requires: tuple[str, ...] = (),
) -> Plan:
    """N independent steps, read together.

    `join` has no default. A fan-in that quietly accepts the first success turns a five-way
    check into a one-way one, and the four steps that disagreed were paid for and discarded.
    """
    return Plan(
        name=name,
        pattern="fan-out",
        join=join,
        quorum=quorum,
        steps=tuple(
            Step(name=f"{name}-{index + 1}", request=request, agent=agent, requires=requires)
            for index, request in enumerate(requests)
        ),
    )


def swarm(
    name: str,
    request: str,
    *,
    attempts: int,
    agents: Sequence[str] = (),
    requires: tuple[str, ...] = (),
) -> Plan:
    """The same task attempted several times, joined by score.

    Always `BEST`, never a race. First-past-the-post selects for speed, and the fastest
    answer is the one that did the least work -- so a raced swarm reliably picks the
    shallowest attempt and pays for the rest.
    """
    if attempts < 2:
        raise PatternError(
            f"a swarm of {attempts} is not a swarm",
            remediation=(
                "Use at least 2. One attempt with the overhead of a swarm is a single run "
                "that costs more and reports less."
            ),
        )
    chosen = list(agents) or [""] * attempts
    if agents and len(chosen) != attempts:
        raise PatternError(
            f"{len(chosen)} agents for {attempts} attempts",
            remediation=(
                "Name one agent per attempt, or none at all. A partial list silently gives "
                "the remaining attempts the default agent, which is not a swarm of the "
                "agents you listed."
            ),
        )
    return Plan(
        name=name,
        pattern="swarm",
        join=Join.BEST,
        steps=tuple(
            Step(
                name=f"{name}-attempt-{index + 1}",
                request=request,
                agent=chosen[index],
                requires=requires,
            )
            for index in range(attempts)
        ),
    )


def critic(
    name: str,
    *,
    produce: str,
    review: str,
    producer: str = "",
    reviewer: str = "",
    requires: tuple[str, ...] = (),
) -> Plan:
    """One agent produces, a different agent judges.

    The two may not be the same agent. Self-review is a rubber stamp with a latency cost,
    and it is the easiest possible way to build a review step that never rejects anything.
    """
    if producer and reviewer and producer == reviewer:
        raise PatternError(
            f"{producer!r} cannot review its own work",
            remediation=(
                "Name a different reviewer. An agent judging its own output approves it, "
                "which makes the review step cost without deciding anything."
            ),
        )
    return Plan(
        name=name,
        pattern="critic",
        join=Join.ALL,
        steps=(
            Step(name=f"{name}-produce", request=produce, agent=producer, requires=requires),
            Step(
                name=f"{name}-review",
                request=review,
                agent=reviewer,
                requires=requires,
                needs=(f"{name}-produce",),
            ),
        ),
    )


def supervisor(
    name: str,
    *,
    plan_request: str,
    worker_requests: Sequence[str],
    join: Join,
    quorum: int = 0,
    supervisor_agent: str = "",
    worker_agent: str = "",
    requires: tuple[str, ...] = (),
) -> Plan:
    """One step plans, N steps execute, and the results are read together."""
    if not worker_requests:
        raise PatternError(
            f"supervisor {name!r} has no workers",
            remediation=(
                "A supervisor with nobody to supervise is one run with an extra hop. "
                "Give it work to hand out, or use a plain step."
            ),
        )
    head = Step(
        name=f"{name}-plan", request=plan_request, agent=supervisor_agent, requires=requires
    )
    workers = tuple(
        Step(
            name=f"{name}-worker-{index + 1}",
            request=request,
            agent=worker_agent,
            requires=requires,
            needs=(head.name,),
        )
        for index, request in enumerate(worker_requests)
    )
    return Plan(
        name=name,
        pattern="supervisor",
        join=join,
        quorum=quorum,
        steps=(head, *workers),
    )


def dag(name: str, steps: Iterable[Step], *, join: Join, quorum: int = 0) -> Plan:
    """Arbitrary edges. The general case the others are shapes of."""
    return Plan(name=name, pattern="dag", join=join, quorum=quorum, steps=tuple(steps))


# ------------------------------------------------------------------------- execution


#: What a runner is handed and what it must return. In production this wraps
#: `Coordinator.run`; in a test it is a dictionary lookup. The engine never learns which.
Runner = Callable[[Step], Outcome]


@dataclass
class Execution:
    """Runs a plan and reads the result.

    Sequential by wave. A caller that wants a wave run concurrently can supply a runner that
    does so; the engine deliberately does not own the concurrency, because a plan that
    dispatches its own threads and a coordinator that leases workers would each be counting
    the fleet's capacity without telling the other.
    """

    runner: Runner
    on_step: Callable[[Step, Outcome], None] | None = None
    stop_early: bool = True
    """Whether to skip steps that can no longer change the answer.

    On by default, and only ever *skips*, never fails. Once `ANY` has its success or `ALL`
    has its failure, the remaining steps cost money to confirm a decision already made. The
    steps that go unrun are recorded as `SKIPPED` precisely so the saving is visible rather
    than looking like a plan that was smaller than it was.
    """

    def run(self, plan: Plan) -> PlanResult:
        outcomes: dict[str, Outcome] = {}
        for wave in plan.order():
            for step in wave:
                blocked = sorted(
                    need for need in step.needs if need not in outcomes or not outcomes[need].ok
                )
                if blocked:
                    outcomes[step.name] = Outcome(
                        step=step.name,
                        state=StepState.SKIPPED,
                        detail=f"never ran: {', '.join(blocked)} did not succeed",
                    )
                    continue
                if self.stop_early and self._settled(plan, outcomes):
                    outcomes[step.name] = Outcome(
                        step=step.name,
                        state=StepState.SKIPPED,
                        detail="never ran: the join was already decided",
                    )
                    continue
                outcome = self.runner(step)
                outcomes[step.name] = outcome
                if self.on_step is not None:
                    self.on_step(step, outcome)

        ordered = tuple(outcomes[step.name] for step in plan.steps)
        return self._join(plan, ordered)

    def _settled(self, plan: Plan, outcomes: dict[str, Outcome]) -> bool:
        """Whether the remaining steps can still change the answer."""
        wins = sum(1 for o in outcomes.values() if o.ok)
        losses = sum(1 for o in outcomes.values() if o.state is StepState.FAILED)
        if plan.join is Join.ALL:
            return losses > 0
        if plan.join is Join.ANY:
            return wins > 0
        if plan.join is Join.QUORUM:
            # Settled when the quorum is reached, or when too few steps remain to reach it.
            remaining = len(plan.steps) - len(outcomes)
            return wins >= plan.quorum or wins + remaining < plan.quorum
        # BEST has to run everything: the best answer cannot be known before the last one.
        return False

    def _join(self, plan: Plan, outcomes: tuple[Outcome, ...]) -> PlanResult:
        wins = [o for o in outcomes if o.ok]
        losses = [o for o in outcomes if o.state is StepState.FAILED]
        skips = [o for o in outcomes if o.state is StepState.SKIPPED]

        def result(satisfied: bool, reason: str, chosen: Outcome | None = None) -> PlanResult:
            return PlanResult(
                plan=plan.name,
                satisfied=satisfied,
                reason=reason,
                outcomes=outcomes,
                chosen=chosen,
            )

        if plan.join is Join.ALL:
            if losses:
                return result(False, f"{len(losses)} step(s) failed: {_names(losses)}")
            if skips:
                # Not satisfied, and the reason says so as "unknown" rather than "no".
                # A plan whose steps were abandoned has not been tested and rejected.
                return result(False, f"{len(skips)} step(s) never ran: {_names(skips)}")
            return result(True, f"all {len(outcomes)} steps succeeded")

        if plan.join is Join.ANY:
            if wins:
                return result(True, f"{_names(wins[:1])} succeeded", wins[0])
            return result(False, f"no step succeeded ({len(losses)} failed, {len(skips)} skipped)")

        if plan.join is Join.QUORUM:
            if len(wins) >= plan.quorum:
                return result(
                    True, f"{len(wins)} of {plan.quorum} required steps succeeded", wins[0]
                )
            return result(
                False,
                f"{len(wins)} of {plan.quorum} required steps succeeded "
                f"({len(losses)} failed, {len(skips)} never ran)",
            )

        scored = [o for o in wins if o.score is not None]
        if not scored:
            # Every attempt may have succeeded and the swarm still has no answer, because
            # nothing scored them. Reported as unsatisfied rather than by picking the first:
            # picking the first is the race this pattern exists to avoid.
            return result(
                False,
                (
                    f"{len(wins)} step(s) succeeded but none was scored; a swarm with no "
                    "score has no way to choose that is not a race"
                ),
            )
        # `max` keeps the first maximal element, so a tie goes to the earlier step. Ties
        # are common -- a gate ratio over three gates has four possible values -- and the
        # rule has to be both deterministic and unsurprising: "the first one that scored
        # this well" is explainable, "the one whose name sorts last" is not.
        best = max(scored, key=lambda o: o.score or 0.0)
        return result(True, f"{best.step} scored highest ({best.score})", best)


def _names(outcomes: Sequence[Outcome]) -> str:
    return ", ".join(o.step for o in outcomes)
