#!/usr/bin/env python3
"""Generate the reference documentation from the definitions that validate (PRD FR-30.4).

NFR-4.3's requirement is that the reference is *produced from* the same definitions the
validator uses, not written alongside them. Documentation written alongside drifts, and the
drift is invisible: a doc describing a gate that was renamed reads perfectly and sends every
reader to a name that does not exist.

So everything here is introspected. Gate names come from the gate registry, error codes from
the enum, CLI commands from the typer app, schemas from the pydantic models. If a name
changes, this output changes; if this output is checked into the repository, CI can tell you
it changed, which is the whole mechanism.

Run: `python scripts/generate_reference.py docs/reference/`
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

GENERATED_NOTE = (
    "<!-- Generated by scripts/generate_reference.py. Do not edit by hand: this file is "
    "produced from the same definitions the validator uses, so that a rename shows up here "
    "rather than leaving a doc that reads correctly and points at a name that no longer "
    "exists (NFR-4.3, FR-30.4). -->\n"
)


def gates_page() -> str:
    from software_factory.evals.gates import BASELINE_GATES

    lines = [
        GENERATED_NOTE,
        "# Gates\n",
        "A gate blocks one run. It answers a yes/no question about *this* change, and its",
        "verdict is binding — which is why the list is short and every entry has to earn its",
        "place. Scorers sample many runs and do not block; benchmarks compare configurations.",
        "Keeping the three apart is deliberate (PRD §7.13).\n",
        "| Gate | Blocks | What it establishes |",
        "| --- | --- | --- |",
    ]
    for name, gate in sorted(BASELINE_GATES.items()):
        summary = (gate.__doc__ or "").strip().splitlines()[0] if gate.__doc__ else ""
        lines.append(f"| `{name}` | yes | {summary} |")
    return "\n".join(lines) + "\n"


def errors_page() -> str:
    from software_factory.errors import ErrorCode

    lines = [
        GENERATED_NOTE,
        "# Error codes\n",
        "Every error this project raises carries a code and a remediation. A code with no",
        "remediation is a message that tells a reader something is wrong and nothing about",
        "what to do, which is the shape of error that gets ignored (FR-2.4).\n",
        "| Code | Meaning |",
        "| --- | --- |",
    ]
    for code in ErrorCode:
        lines.append(f"| `{code.value}` | {code.name.replace('_', ' ').capitalize()} |")
    return "\n".join(lines) + "\n"


def tools_page() -> str:
    from software_factory.runtime.tools import BUILTIN_TOOL_EFFECTS

    lines = [
        GENERATED_NOTE,
        "# Built-in tools\n",
        "Every tool declares the effect class it needs. An agent granted `read` cannot call a",
        "`write` tool however its prompt is worded — grants come from configuration, and text",
        "cannot widen them (FR-10, FR-17.5).\n",
        "This table is generated from the same map `build_registry` reads, so a static audit",
        "and the running registry cannot disagree.\n",
        "| Tool | Effect |",
        "| --- | --- |",
    ]
    for name, effect in sorted(BUILTIN_TOOL_EFFECTS.items()):
        lines.append(f"| `{name}` | `{effect.value}` |")
    return "\n".join(lines) + "\n"


def capabilities_page() -> str:
    from software_factory.identity.principals import PERSON_ONLY, Capability

    lines = [
        GENERATED_NOTE,
        "# Capabilities\n",
        "Authority is granted per capability rather than per person-in-general. There is no",
        "`admin` here on purpose: `approve_spec` and `erase_data` are different powers, and a",
        "role that bundles them is a role nobody can reason about (FR-25.2).\n",
        "Capabilities marked **person only** may never be held by an agent. Granting one to an",
        "agent does not delegate the checkpoint; it deletes it — so `sf validate` refuses the",
        "grant rather than honouring it.\n",
        "| Capability | Person only |",
        "| --- | --- |",
    ]
    for capability in Capability:
        marker = "**yes**" if capability in PERSON_ONLY else "no"
        lines.append(f"| `{capability.value}` | {marker} |")
    return "\n".join(lines) + "\n"


def stages_page() -> str:
    from software_factory.orchestrator import (
        DEFAULT_NON_SKIPPABLE,
        DEFAULT_ORDER,
        DEFAULT_TRANSITIONS,
    )

    lines = [
        GENERATED_NOTE,
        "# Stages\n",
        "The default stage graph. This is *data*, not architecture: a factory may declare its",
        "own, subject to the invariants `validate_graph` checks (FR-4.2a).\n",
        "A stage marked non-skippable cannot be skipped on an agent's authority. Skipping needs",
        "a principal holding `skip_stage`, and the approval is recorded against their identity.\n",
        "Declared order: " + " → ".join(s.value for s in DEFAULT_ORDER) + "\n",
        "| Stage | May move to | Non-skippable |",
        "| --- | --- | --- |",
    ]
    for stage in DEFAULT_ORDER:
        targets = DEFAULT_TRANSITIONS.get(stage, frozenset())
        marker = "**yes**" if stage in DEFAULT_NON_SKIPPABLE else ""
        lines.append(
            f"| `{stage.value}` | {', '.join(f'`{t.value}`' for t in sorted(targets, key=lambda s: s.value)) or '_terminal_'} | {marker} |"
        )
    return "\n".join(lines) + "\n"


def data_classes_page() -> str:
    from software_factory.governance import DEFAULT_CLASSIFICATION

    lines = [
        GENERATED_NOTE,
        "# Data classes\n",
        "What each persisted class can contain and how long it is kept. A retention policy that",
        "does not say what is *in* the thing being retained is a number with no argument behind",
        "it (FR-27.1).\n",
        "| Class | May contain | Retention | Erasable by subject |",
        "| --- | --- | --- | --- |",
    ]
    for rule in DEFAULT_CLASSIFICATION.values():
        contains = ", ".join(f"`{s.value}`" for s in sorted(rule.contains, key=lambda s: s.value))
        if rule.retention is None:
            kept = "until erased"
        else:
            seconds = int(rule.retention.total_seconds())
            kept = f"{seconds // 86400}d" if seconds >= 86400 else f"{seconds // 3600}h"
        erasable = "yes" if rule.erasable_by_subject else "**no**"
        lines.append(f"| `{rule.data_class.value}` | {contains} | {kept} | {erasable} |")
    return "\n".join(lines) + "\n"


def cli_page() -> str:
    import typer

    from software_factory.cli import app

    lines = [
        GENERATED_NOTE,
        "# CLI\n",
        "Every command answers a question a person actually asks. `--json` on any of them emits",
        "machine-readable output, because a CLI that can only be read by a human is one that",
        "cannot be scripted, and PR-2 makes the local path the reference one.\n",
        "**Exit codes.** `0` the question was answered; `1` the answer is bad news — a gate",
        "blocked, a check failed; `3` the question cannot be answered here — no factory, no",
        "ledger, no configured provider. `2` is left to the argument parser and means the",
        "command line itself could not be read. `1` and `3` are kept apart for the same reason",
        "every metric here separates *unavailable* from *zero*: a script that cannot tell a",
        "mistyped flag from an empty ledger will treat one as the other.\n",
        "| Command | What it answers |",
        "| --- | --- |",
    ]

    def describe(command: typer.models.CommandInfo, prefix: str = "") -> None:
        name = f"{prefix}{command.name or (command.callback.__name__ if command.callback else '')}"
        doc = (command.callback.__doc__ or "").strip() if command.callback else ""
        summary = doc.splitlines()[0] if doc else ""
        lines.append(f"| `sf {name}` | {summary} |")

    for command in sorted(app.registered_commands, key=lambda c: c.name or ""):
        describe(command)
    for group in sorted(app.registered_groups, key=lambda g: g.name or ""):
        typer_instance = group.typer_instance
        if typer_instance is None:
            continue
        for command in sorted(typer_instance.registered_commands, key=lambda c: c.name or ""):
            describe(command, prefix=f"{group.name} ")
    return "\n".join(lines) + "\n"


PAGES = {
    "gates.md": gates_page,
    "errors.md": errors_page,
    "tools.md": tools_page,
    "capabilities.md": capabilities_page,
    "stages.md": stages_page,
    "data-classes.md": data_classes_page,
    "cli.md": cli_page,
}


def main(argv: list[str]) -> int:
    # Flags filtered out before reading the positional argument. Taking `argv[1]` blindly
    # made `--check` the output directory, so the check compared the real pages against an
    # empty `./--check/` and reported every one of them stale -- a check that always fails
    # is a check that gets switched off.
    check_only = "--check" in argv[1:]
    positional = [arg for arg in argv[1:] if not arg.startswith("-")]
    out_dir = Path(positional[0]) if positional else REPO_ROOT / "docs" / "reference"

    out_dir.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for filename, builder in sorted(PAGES.items()):
        content = builder()
        path = out_dir / filename
        if check_only:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(filename)
            continue
        path.write_text(content, encoding="utf-8")

    if check_only:
        if stale:
            print(
                "The generated reference is out of date: " + ", ".join(stale) + "\n"
                "Run `python scripts/generate_reference.py` and commit the result. These "
                "pages are generated from the definitions themselves, so a difference here "
                "means a name changed and the docs still point at the old one."
            )
            return 1
        print("the generated reference matches the definitions")
        return 0

    print(f"wrote {len(PAGES)} reference page(s) to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
