#!/usr/bin/env python3
"""Run the end-to-end product trials and write the report.

    python scripts/run_trials.py [output.md]

Exits non-zero when a trial's expectation did not hold, so this is usable in CI. The
distinction the exit code encodes: an expectation that failed is a *surprise*, and a trial
whose surprises are empty is one whose expectations all held -- which is a stronger and
narrower claim than "the trials ran".
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

# The repository root, so `trials` imports whether this is run from the root or elsewhere.
# `scripts/` is not a package and adding one to make an import work would be a package that
# exists for the import.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from trials import adversarial, brownfield, greenfield

TRIALS = [
    ("greenfield", greenfield.run),
    ("brownfield", brownfield.run),
    ("adversarial", adversarial.run),
]

PREAMBLE = """\
# Product trials

Generated by `python scripts/run_trials.py`. Not written by hand, for the same reason
`docs/reference/` is generated: a report of what the system does, maintained separately from
the system, describes what it used to do.

Every trial runs a real repository through the factory -- real git history, the repository's
own pytest suite, real diffs, and gates evaluating the actual result. **The model is
scripted**, because no live provider is reachable from the environment these were run in.
That boundary is the most important thing on this page: these trials establish that *given*
an output, the factory does the right thing with it. They establish nothing about whether a
modest model inside this harness produces good output, which is the project's central bet
and what §11.2 of the PRD exists to test.

Each trial reports what it established, what it does not, and any surprises -- expectations
that did not hold. A trial with surprises is not a failure to hide; it is the trial working.
"""


def main() -> int:
    destination = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("docs/trials.md")
    sections: list[str] = [PREAMBLE]
    surprises = 0

    for name, run in TRIALS:
        with tempfile.TemporaryDirectory(prefix=f"sf-trial-{name}-") as directory:
            report = run(Path(directory))
        sections.append(report.render())
        surprises += len(report.surprises)
        state = "clean" if not report.surprises else f"{len(report.surprises)} surprise(s)"
        print(f"{name:<12} {report.final_stage:<9} {state}")

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n\n---\n\n".join(sections) + "\n", encoding="utf-8")
    print(f"\nwrote {destination}")
    return 1 if surprises else 0


if __name__ == "__main__":
    raise SystemExit(main())
