#!/usr/bin/env python3
"""Run the stress scenarios and write `docs/stress.md`.

Separate from `run_trials.py` because the questions differ. A trial asks whether the
factory does the right thing on one work item; a stress run asks whether it keeps doing the
right thing when several things happen at once, when the ledger is large, when a provider
misbehaves, and when the text coming back is hostile rather than merely wrong.

Exits non-zero on any surprise, so it can gate a merge. Every scenario runs even when an
earlier one fails: a stress run that stops at its first surprise reports one problem when it
could have reported five, and the second is often what explains the first.

    python scripts/run_stress.py [--only NAME] [--out docs/stress.md]
"""

from __future__ import annotations

import argparse
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from stress.harness import StressReport, timed
from stress.scenarios import SCENARIOS

HEADER = """# Stress report

| Field | Value |
| --- | --- |
| Generated by | `python scripts/run_stress.py` |
| Generated at | {when} |
| Scenarios | {count} |
| Surprises | {surprises} |

These ask what the trials do not: whether the factory keeps behaving when several things
happen at once, when the ledger is large, when a provider misbehaves, and when the text
coming back is hostile rather than merely wrong. The failures those find differ in kind — a
corrupt ledger, a lost entry, a number that was right at ten runs and wrong at ten thousand,
a crash that takes the process with it. None of them show up on a happy path, and all of
them are what an operator meets first.

Thresholds here are deliberately loose. They exist to catch a change that makes something
*orders* worse, not to police a few hundred milliseconds on a shared runner.

"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--only", default=None, help="Run one scenario by name.")
    parser.add_argument("--out", default="docs/stress.md", help="Where to write the report.")
    args = parser.parse_args()

    chosen = {args.only: SCENARIOS[args.only]} if args.only else dict(SCENARIOS)
    if args.only and args.only not in SCENARIOS:
        print(f"unknown scenario {args.only!r}; known: {', '.join(SCENARIOS)}", file=sys.stderr)
        return 2

    reports: list[StressReport] = []
    for name, scenario in chosen.items():
        with tempfile.TemporaryDirectory(prefix=f"sf-stress-{name}-") as directory:
            report = StressReport(name=name, description="")
            # The scenario builds its own report; this one is a placeholder so a scenario
            # that raises before returning still appears in the output.
            built = timed(report, lambda r, s=scenario, d=directory: _run(r, s, Path(d)))
            reports.append(built)
        print(built.render(), file=sys.stderr)
        print(file=sys.stderr)

    surprises = sum(len(r.surprises) for r in reports) + sum(1 for r in reports if r.error)
    body = HEADER.format(
        when=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
        count=len(reports),
        surprises=surprises or "none",
    )
    for report in reports:
        body += f"## {report.name}\n\n{report.description}\n\n"
        body += f"Ran in {report.seconds:.1f}s.\n\n"
        if report.facts:
            body += "| Fact | Value |\n| --- | --- |\n"
            for key, value in sorted(report.facts.items()):
                body += f"| {key} | {value} |\n"
            body += "\n"
        body += "| Check | Result |\n| --- | --- |\n"
        for finding in report.findings:
            mark = "ok" if finding.ok else "**FAILED**"
            detail = f" — {finding.detail}" if finding.detail else ""
            body += f"| {finding.claim} | {mark}{detail} |\n"
        if report.error:
            body += f"\n**The scenario raised:** `{report.error}`\n"
        body += "\n"

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out}", file=sys.stderr)
    return 1 if surprises else 0


def _run(placeholder: StressReport, scenario, directory: Path) -> None:
    """Run one scenario, copying its report onto the placeholder.

    The placeholder exists so a scenario that raises before it returns anything still shows
    up in the report with its error, rather than vanishing.
    """
    built = scenario(directory)
    placeholder.name = built.name
    placeholder.description = built.description
    placeholder.findings = built.findings
    placeholder.facts = built.facts


if __name__ == "__main__":
    raise SystemExit(main())
