"""The self-improvement loop and its anti-capture defences (PRD FR-14)."""

from software_factory.improvement.clustering import (
    MIN_CLUSTER_SIZE,
    SPLIT_THRESHOLD,
    Cluster,
    Failure,
    cluster_failures,
)
from software_factory.improvement.loop import (
    DEFAULT_COOLING,
    DEFAULT_MAX_OPEN,
    DRIFT_TOLERANCE,
    MIN_LOOP_EFFECT,
    DriftFinding,
    LoopState,
    ProposalRecord,
    ProposalStatus,
    Refused,
    Telemetry,
    check_effectiveness,
    detect_drift,
    disable,
    may_propose,
    settle,
    submit,
    suspend_for_drift,
    telemetry,
)

__all__ = [
    "DEFAULT_COOLING",
    "DEFAULT_MAX_OPEN",
    "DRIFT_TOLERANCE",
    "MIN_CLUSTER_SIZE",
    "MIN_LOOP_EFFECT",
    "SPLIT_THRESHOLD",
    "Cluster",
    "DriftFinding",
    "Failure",
    "LoopState",
    "ProposalRecord",
    "ProposalStatus",
    "Refused",
    "Telemetry",
    "check_effectiveness",
    "cluster_failures",
    "detect_drift",
    "disable",
    "may_propose",
    "settle",
    "submit",
    "suspend_for_drift",
    "telemetry",
]
