"""Loom: the agent harness.

The harness is the product. See ``docs/harness/HARNESS.md`` for the design and
``docs/PRD.md`` §7.9-§7.12 for the requirements.
"""

from software_factory.harness.awareness import (
    PACK_BUDGET_FRACTION,
    ROLE_WEIGHTS,
    AwarenessPack,
    Citation,
    CitationKind,
    Item,
    Origin,
    PackAssembler,
    Section,
    SectionId,
    Snapshot,
    estimate_tokens,
)
from software_factory.harness.routing import (
    Decomposition,
    Escalation,
    EscalationRefused,
    RoutingState,
    Scaffold,
    Step,
    Trigger,
    VerifierClass,
    may_escalate,
    scaffolds_for,
    starting_tier,
)
from software_factory.harness.tools import (
    BlastRadius,
    Calibration,
    CalibrationCriterion,
    CostClass,
    Example,
    FailureKind,
    Grants,
    Tool,
    ToolFailure,
    ToolRegistry,
    ToolRegistryError,
    ToolSuccess,
    Violation,
    calibration_error,
)

__all__ = [
    "PACK_BUDGET_FRACTION",
    "ROLE_WEIGHTS",
    "AwarenessPack",
    "BlastRadius",
    "Calibration",
    "CalibrationCriterion",
    "Citation",
    "CitationKind",
    "CostClass",
    "Decomposition",
    "Escalation",
    "EscalationRefused",
    "Example",
    "FailureKind",
    "Grants",
    "Item",
    "Origin",
    "PackAssembler",
    "RoutingState",
    "Scaffold",
    "Section",
    "SectionId",
    "Snapshot",
    "Step",
    "Tool",
    "ToolFailure",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolSuccess",
    "Trigger",
    "VerifierClass",
    "Violation",
    "calibration_error",
    "estimate_tokens",
    "may_escalate",
    "scaffolds_for",
    "starting_tier",
]
